# Generated by Django 5.1.4 on 2025-01-15 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_usersession'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSession',
        ),
    ]
